apiVersion: v1
kind: ConfigMap
metadata:
  name: api-banking-statistics-nginx-conf
  namespace: api-banking-temp
data:
  nginx.conf: |
   worker_processes  1;
   events {
       worker_connections  1024;
   }
   http {
       include       mime.types;
       default_type  application/octet-stream;
       sendfile        on;
       keepalive_timeout  65;
       server {
         listen       8443 ssl;
         ssl_certificate      /app/cert/ssl-bundle.crt;
         ssl_certificate_key  /app/cert/ocp.key;
         ssl_protocols TLSv1.2;
         ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:!EECDH+3DES:!RSA+3DES:!MD5;
         ssl_prefer_server_ciphers on;
         location / {
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header Host $http_host;
           proxy_pass http://127.0.0.1:8080/; 
         }
       }
   }