apiVersion: v1
data:
 ocp.crt: -----BEGIN CERTIFICATE-----
MIIDZTCCAk0CFCZDZd4KFKkcusvbdU6ZBMSQqv2BMA0GCSqGSIb3DQEBCwUAMG8x
CzAJBgNVBAYTAlNHMRIwEAYDVQQHDAlTaW5nYXBvcmUxGzAZBgNVBAoMElN0YW5k
YXJkIENoYXJ0ZXJlZDEvMC0GA1UEAwwmYXBwcy5kY2RhLW5wLm9jcC5zdGFuZGFy
ZGNoYXJ0ZXJlZC5jb20wHhcNMjAwNzI0MDE0ODQxWhcNMjEwNzI0MDE0ODQxWjBv
MQswCQYDVQQGEwJTRzESMBAGA1UEBwwJU2luZ2Fwb3JlMRswGQYDVQQKDBJTdGFu
ZGFyZCBDaGFydGVyZWQxLzAtBgNVBAMMJmFwcHMuZGNkYS1ucC5vY3Auc3RhbmRh
cmRjaGFydGVyZWQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
5EGtusthly9AQJL7IT0uS0Vxj0MqUBvagHVXybtjDUWv9QmnokJdWsa96XTmZcv+
XYfQ4XLWhpKQQPzq83Xue3vpWdjbXR2JfUTCTBR3+39v82WWLs7pxN8muwtEz6+T
/RavNMLPCI6hEGWQcEdNPhT+BRkBM4q8KntSTISUHDeBvJJYShLOjL5zfzgzKdee
u7x9IdqxInLPNdEuPfMPxfl2fKGOFrpGV1CkLvCVBnq0LiUWbcNKAAwV31sb2Doh
nTC/enkfaG2TccmFj+A1ku2ZaGP/+xc3Q4NBnZ1KnqlShvnqK5vNFFhC1xLMg3sq
Xea7BQmpqlC/6XW1WesBNwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCCEB+rEnI2
oc0kd83DeZIgLvTLXtw4WekEeKr1jsppuKYtinrcztoYqlOTAhjypLRPNLeNn6yz
lNbYcF5kGNmCtQI+oTfBgsfW9PDLvHljAp8ITs6VdHcrMrMzaHV49pve90/Ol/ax
B0gd8bg2hKA3jyDxKf4aOttw6Kd0rvlxjEhLXC0OFAtds0IP8qdt4cTYct8aibys
h9kZdAV5Ctkq5KsoglHdVmfim3bKBTfBADfhnRuNapL6dNu+RdXo06gIYynxtp1W
7xB3Mc/N3WER7NrIsQT6kM+YK9GrsF6yYFNB53mKxY2IqKBRJEi8gSUNRJCaO3KN
jkmSVH3sKCu7
-----END CERTIFICATE-----
 ocp.key: -----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDkQa26y2GXL0BA
kvshPS5LRXGPQypQG9qAdVfJu2MNRa/1CaeiQl1axr3pdOZly/5dh9DhctaGkpBA
/Orzde57e+lZ2NtdHYl9RMJMFHf7f2/zZZYuzunE3ya7C0TPr5P9Fq80ws8IjqEQ
ZZBwR00+FP4FGQEzirwqe1JMhJQcN4G8klhKEs6MvnN/ODMp1567vH0h2rEics81
0S498w/F+XZ8oY4WukZXUKQu8JUGerQuJRZtw0oADBXfWxvYOiGdML96eR9obZNx
yYWP4DWS7ZloY//7FzdDg0GdnUqeqVKG+eorm80UWELXEsyDeypd5rsFCamqUL/p
dbVZ6wE3AgMBAAECggEAd/JHoBxWOUM8SXKzgyEKXcWtSjJqXtR0OwLu0fSltYjE
UUj0jWDAe/5qN+8VT7MmBPJlAsP9FZSZN31w3eVAICXaVzuM8t6drHVggOhUsJWk
N8xPYmObFriJOstOKrFCXEH6aghhEUcaPmqQv1/IqHIRlo4wQmyKOuy5L7qPtk86
tkouwv+/BgYYp8dOc8Nh8CvvVMd06LdZ5VLhfqXzQ0nOeHxR1+4Uqt8Jbh/UhAc4
0mP9hE3u2MrXwj7IEWPp9Fue2m3NeZClz0aN4BUDSrZZ6TrTiMfZACxo/jbcm9nF
5ACAPcfgI/VGcVxN0XXwsWB2MCCFSwsehAqelOzQ8QKBgQD4pKmxUObc5r+gyLnD
mXR+mAMt/RjnmZETrfQ//7fwhVlrBeH3dQ3lk7Wdg2klACI8qXnbYuxCCkdkJMvH
4BAfGIaGeCZV4gyMAdbXHo3fTEkIna55I8Fq+J5759Ilmslzogd/I3uCYMo+B6lB
SqepPyOJYk4Z+u1gJvqDB50ZeQKBgQDrApkRzD9lphsjsZDYwQZ/8ADDVIxQPfke
+kPkeLx259yuW6H+U3llIqMDxviqlDjWtrKAT/Pi9VyfQYohNIf5Kjm7IYYpDoGu
bCliB5jEGXrd6M00NsreaF048EX/jYJUjWht8YzIiSinTOIRdOetdU8Mu1Magflp
64Uszyz0LwKBgBwf3AXvhb2U6DYSnliOoguzvCBWkZuY1j0onwkiLrcpDj051B5+
ggzm0VM4ywrhYf4EmYEERn8N1JdyRg6cvJYX2xeYvZVXVV3800VP8nJAmb48v8B6
F+W2q46OYUnZoVHQERMDe3P66MVtbmqxPBe7yZQ/p1/u7yzCG/H4SX/ZAoGBAK7q
2Rl5J3q1/p87i675RKg276pzJJiY9/JJnfzQrJ3oB8Yy58jPQpy3AhROpUj5V7Dg
fM2qNMGplE3ozzHV0prvBdc1pZCrfnRfhxGyy86xlFTU8N87JRYTIce+dqs2HVpn
geHLFtkv1XVocR9DHylpFfRI/RrOwOBIb3Ahp7j7AoGBAJld2S1r/wV/FmmSJGg2
Ckc5MlP4qsX2GeEMcOzlmZAp7epvzeL9/41sOhCYNe3rhoBAkOfweLt1dVY6aoTa
WdLJOciqn7DBGuhTeGnYD7pRVTozHYnahkVJHeUclRqRKTsWcTBXF2VYofNfAup0
poVfGmXgo8syljk61bw/VND0
-----END PRIVATE KEY-----
kind: Secret
metadata:
 name: api-banking-statistics-nginx-secret
 namespace: api-banking-temp
type: Opaque