apiVersion: v1
kind: Service
metadata:
  name: api-banking-statistics-nginx-service
  namespace: api-banking-temp
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: api-banking-statistics
  sessionAffinity: None
  type: ClusterIP