apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: spark
  creationTimestamp: "2020-12-29T15:04:50Z"
  generation: 1
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spark
    helm.sh/chart: spark-4.4.0
  name: my-release-spark-worker
  namespace: spark
  resourceVersion: "24015674"
  selfLink: /apis/apps/v1/namespaces/spark/statefulsets/my-release-spark-worker
  uid: 0ad95768-369e-4297-8292-258a2e480f94
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: spark
  serviceName: my-release-spark-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: spark
        helm.sh/chart: spark-4.4.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: worker
                  app.kubernetes.io/instance: my-release
                  app.kubernetes.io/name: spark
              namespaces:
              - spark
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: SPARK_MODE
          value: worker
        - name: BASH_DEBUG
          value: "0"
        - name: SPARK_DAEMON_MEMORY
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_DAEMON_JAVA_OPTS
        - name: SPARK_MASTER_URL
          value: spark://my-release-spark-master-svc:7077
        - name: SPARK_WORKER_OPTS
        image: docker.io/bitnami/spark:3.0.1-debian-10-r87
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: spark-worker
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: my-release-spark-worker-777ddd585
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updateRevision: my-release-spark-worker-777ddd585
  updatedReplicas: 2
